class UserStates:
    INIT = "INIT"
    WAITING_NAME = "WAITING_NAME"
    EMAIL_SENT = "EMAIL_SENT"
    WAITING_MODERATION = "WAITING_MODERATION"
    ONBOARDING = "ONBOARDING"
    READY_STATUS = "READY_STATUS"
    CLUBS = "CLUBS"
    CREATE_MEETING = "CREATE_MEETING"