#здесь мы просто устанавливаем связь между бд и бэкэндом, в логику углубляться не надо
version: '3.5'

services:
  postgres:
    container_name: kode_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: luch1x
      POSTGRES_PASSWORD: Fq12Ww
      POSTGRES_DB: KODE-practice
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - kode_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kode_network
    restart: unless-stopped
  
  pgadmin:
    container_name: kode_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kode.local
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - kode_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - kode_network
    restart: unless-stopped

networks:
  kode_network:
    driver: bridge

volumes:
  kode_postgres_data:
  kode_pgadmin_data:
